# Generated by Django 4.1.1 on 2022-10-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.CharField(max_length=255, verbose_name='Транзакция ID')),
                ('merchant_trans_id', models.CharField(max_length=255, verbose_name='Merchant транзакция ID')),
                ('amount', models.CharField(max_length=255, verbose_name='Сумма оплаты (в сумах)')),
                ('action', models.CharField(max_length=255, verbose_name='Выполняемое действие')),
                ('sign_string', models.CharField(max_length=255, verbose_name='Проверочная строка, подтверждающая подлинность отправляемого запроса.')),
                ('sign_datetime', models.DateTimeField(max_length=255, verbose_name='Дата платежа')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('finished', 'finished'), ('canceled', 'canceled')], default='processing', max_length=25, verbose_name='Статус')),
            ],
        ),
    ]
